#!/data/data/com.termux/files/usr/bin/sh
termux-wake-lock
sshd
sv-enable crond
dumpsys battery set level 100
svc power stayon true
dumpsys deviceidle whitelist +com.termux.boot
dumpsys deviceidle whitelist +com.termux
settings put global system_capabilities 100
settings put global sem_enhanced_cpu_responsiveness 1
settings put global wifi_sleep_policy 2
~/ccminer/start.sh
